#!/usr/bin/env python
# mbs 2014-05-04, for openshift "ortho"
 
import os
import sys
 
#todo debug only, can be removed:
#print('----------------------')
#print('path=', sys.path)
#print('OPENSHIFT_REPO_DIR=', os.environ['OPENSHIFT_REPO_DIR'])
#print('joined=', os.path.join(os.environ['OPENSHIFT_REPO_DIR'], 'ortoloco'))
#print('----------------------')

sys.path.append(os.path.join(os.environ['OPENSHIFT_REPO_DIR'], 'ortoloco'))
sys.path.append(os.path.join(os.environ['OPENSHIFT_REPO_DIR']))
#sys.path.append(os.path.join(os.environ['OPENSHIFT_REPO_DIR'], 'wsgi', 'openshift'))
os.environ['DJANGO_SETTINGS_MODULE'] = 'ortoloco.settings'
#os.environ['DJANGO_SETTINGS_MODULE'] = 'openshift.settings'
 
virtenv = os.environ['OPENSHIFT_HOMEDIR'] + 'python-2.6/virtenv/'
#virtenv = os.environ['APPDIR'] + '/virtenv/'
os.environ['PYTHON_EGG_CACHE'] = os.path.join(virtenv, 'lib/python2.6/site-packages')
 
virtualenv = os.path.join(virtenv, 'bin/activate_this.py')
try:
    execfile(virtualenv, dict(__file__=virtualenv))
except IOError:
    pass
#
# IMPORTANT: Put any additional includes below this line.  If placed above this
# line, it's possible required libraries won't be in your searchable path
#
 
import django.core.handlers.wsgi
application = django.core.handlers.wsgi.WSGIHandler()
